version: "3.8"
services:
  frontend:
    build: ./frontend
    image: ajxbutt/fantasy-football-frontend:latest
    container_name: fantasy-football-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: ajxbutt/fantasy-football-backend:latest
    container_name: fantasy-football-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
      - target: 5000
        published: 5000