version: "3.8"
services:
  frontend:
    deploy:
      replicas: 1
    build: ./frontend
    image: ajxbutt/fantasy-football_frontend:latest
    container_name: fantasy-football_frontend
    ports:
    - target: 5000
      published: 80
  backend:
    deploy:
      replicas: 1
    build: ./backend
    image: ajxbutt/fantasy-football_backend:latest
    container_name: fantasy-football_backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
      - target: 5000
        published: 5000